#!/usr/bin/env ruby
#
require "azure"
require "yaml"

def ask
    puts
    puts "*********************"
    puts "Choose Option:
    0. Exit
    1. List Storage Accounts
    2. Delete all storage Accounts
    3. List all vm images
    4. List Cloud Services
    5. List all disks
    "
    puts "*********************"
    puts
    n = gets.chomp.to_i
end

def get_sa
    puts "please wait..."
    sm = Azure.storage_management
    sm.list_storage_accounts.each do |storage|
        puts storage.name
    end
end

def rm_sa
    puts "please wait..."
    sm = Azure.storage_management
    sm.list_storage_accounts.each do |storage|
        begin
            sm.delete_storage_account(storage.name)
            puts "    #{storage.name} removed"
        rescue Exception => e
            puts "cannot delete #{storage.name}"
            puts "due to #{e.message}"
        end
    end
end

def get_cs
    puts "please wait..."
    cm = Azure.cloud_service_management
    cm.list_cloud_services.each do |service|
        puts service.name
        cm.delete_cloud_service(service.name)
    end
end

# Get a list of available virtual machine images
def get_vmi
    puts "please wait..."
    vm_image_management = Azure.vm_image_management
    vm_image_management.list_virtual_machine_images.each do |vm|
        puts
        puts vm.name
        puts vm.locations
        puts
    end
end

CONFIG = "config"
@account = YAML::load(File.read(CONFIG))

_services = @account['services']
_az = _services['azure']

Azure.configure do |config|
          config.management_certificate = _az['pem_management_cert']
          config.subscription_id        = _az['subscription_id']
          config.management_endpoint    = _az['management_endpoint']
end


puts "************************"
puts "****AZURE CLASSIC*******"
puts "************************"
puts

n = -1
while n != 0 do
    n = ask
    case n
      when 0
          puts "bye"
      when 1
          get_sa
      when 2
          rm_sa
      when 3
          get_vmi
      when 4
          get_cs
        # code
      else
        puts "not valid!"
    end
end
